fix(ci): coverage report WIP

diff --git a/.github/workflows/coverage-report.yml b/.github/workflows/coverage-report.yml
--- a/.github/workflows/coverage-report.yml
+++ b/.github/workflows/coverage-report.yml
@@ -12,7 +12,7 @@
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
-# limitations under the License. 
+# limitations under the License.
 # ---------------------------------------------------------------------------
 
 name: coverage report
@@ -36,75 +36,70 @@ jobs:
           go-version: '1.18'
           check-latest: true
 
-      - name: Get Old Coverage
+      - name: Prepare repo configuration
         shell: bash
-        run: |
-          git clone https://github.com/apache/camel-k.git
-          cd camel-k
-          old_coverage="$(grep -o -P '(?<=Coverage-)(.*)(?=%)' README.adoc)"
-          cd ..
-          rm -rf camel-k
-
-      - name: Checkout
-        shell: bash
-        run: |
-          git clone ${{github.server_url}}/${{ github.repository }}.git
-          cd camel-k
-          git checkout ${{ github.event.pull_request.head.ref }}
-
-      - name: Fetch
-        shell: bash
-        working-directory: ./camel-k
         env:
           CI_USER: "github-actions[bot]"
           CI_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
         run: |
+          git clone ${{ github.event.pull_request.head.repo.clone_url }}
+          cd ${{ github.event.pull_request.head.repo.name }}
+          git checkout ${{ github.event.pull_request.head.ref }}
+
           git config --local user.email "$CI_EMAIL"
           git config --local user.name "$CI_USER"
-          git remote add upstream https://github.com/apache/camel-k.git
+          git remote add upstream ${{ github.event.pull_request.base.repo.clone_url }}
           git fetch upstream
-          
+
       - name: Rebase
         shell: bash
-        working-directory: ./camel-k
+        working-directory: ./${{ github.event.pull_request.head.repo.name }}
         env:
           CI_USER: "github-actions[bot]"
           CI_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
           CI_TOKEN: ${{ inputs.secretGithubToken }}
         run: |
-          git pull --rebase upstream main && echo "rebaseAborted=0" >> $GITHUB_ENV || echo "rebaseAborted=1" >> $GITHUB_ENV
+          git pull --rebase upstream ${{ github.event.pull_request.base.ref }} && echo "rebaseAborted=0" >> $GITHUB_ENV || echo "rebaseAborted=1" >> $GITHUB_ENV
 
       - name: Get New Coverage
         shell: bash
-        working-directory: ./camel-k
+        working-directory: ./${{ github.event.pull_request.head.repo.name }}
         if: env.rebaseAborted != 1
-        env:
-          CI_USER: "github-actions[bot]"
-          CI_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
-          CI_TOKEN: ${{ inputs.secretGithubToken }}
         run: |
           go test -v ./... -covermode=count -coverprofile=coverage.out
           go tool cover -func=coverage.out -o=coverage.out
 
           new_coverage="$(grep -o -P '(?<=\(statements\))(.+)(?=%)' coverage.out | xargs)"
+          echo "NEW_COV=$new_coverage" >> $GITHUB_ENV
 
+      - name: Get Old Coverage
+        shell: bash
+        working-directory: ./${{ github.event.pull_request.head.repo.name }}
+        if: env.rebaseAborted != 1
+        run: |
+          git checkout upstream/${{ github.event.pull_request.base.ref }}
+          go test -v ./... -covermode=count -coverprofile=coverage.out
+          go tool cover -func=coverage.out -o=coverage.out
+
+          old_coverage="$(grep -o -P '(?<=\(statements\))(.+)(?=%)' coverage.out | xargs)"
+          echo "OLD_COV=$old_coverage" >> $GITHUB_ENV
+
+      - name: Process results
+        shell: bash
+        working-directory: ./${{ github.event.pull_request.head.repo.name }}
+        if: env.rebaseAborted != 1
+        run: |
           echo "OLD - $old_coverage"
           echo "NEW - $new_coverage"
-
           coverage_difference=$(bc <<< $new_coverage-$old_coverage)
-
           if (( $(echo "$coverage_difference > 0" |bc -l) )); then
-          echo "POS_DIFF=POS" >> $GITHUB_ENV
+            echo "POS_DIFF=POS" >> $GITHUB_ENV
           elif (( $(echo "$coverage_difference < 0" |bc -l) )); then
-          echo "POS_DIFF=NEG" >> $GITHUB_ENV
+            echo "POS_DIFF=NEG" >> $GITHUB_ENV
           else
-          echo "POS_DIFF=ZERO" >> $GITHUB_ENV
+            echo "POS_DIFF=ZERO" >> $GITHUB_ENV
           fi
-
-          echo "NEW_COV=$new_coverage" >> $GITHUB_ENV
-          echo "OLD_COV=$old_coverage" >> $GITHUB_ENV
           echo "COV_DIFF=$coverage_difference" >> $GITHUB_ENV
-         
 
       - name: Comment Coverage
         if: env.rebaseAborted != 1
